### ISSUE TITLE
Consider using external-svg-sprite-loader

### ISSUE THREAD

**Issue by satazor** [moxystudio/react-with-moxy#4]
Benefits of using [external-svg-sprite-loader](https://github.com/Karify/external-svg-sprite-loader):

- Creates an svg sprite file, e.g.: svg-sprite.svg, which is a highly cacheable file
- Since `<svg>`'s src point to the svg-sprite.svg, it means that sprites are loaded asynchronously which do not block the initial page load
- We can deliver gzip compression on the sprite file

**At the moment, we can't use this loader because it's incompatible with webpack2, see: https://github.com/Karify/external-svg-sprite-loader/issues/10**

Considerations to have in mind when adding this loader:
- Use [svgxuse](https://github.com/Keyamoon/svgxuse) instead of [svg4everbody](https://github.com/jonathantneal/svg4everybody) to polyfill IE11
- Create an `deferrable` entrypoint in webpack that includes `svgxuse` and load it with `<script async defer>`
- Offer a SVG component to be used with the following contents:

```js
import React, { PureComponent, PropTypes } from 'react';
import classnames from 'classnames';
import './SvgIcon.css';

// See https://github.com/Karify/external-svg-sprite-loader

class SvgIcon extends PureComponent {
    render() {
        const { svg, className, title, ...props } = this.props;

        return (
            <svg className={ classnames('svg-icon', className) } viewBox={ svg.viewBox } { ...props }>
                <title>{ title }</title>
                <use xlinkHref={ svg.symbol } />
            </svg>
        );
    }
}

SvgIcon.propTypes = {
    svg: PropTypes.object.isRequired,
    title: PropTypes.string,
    className: PropTypes.string,
};

export default SvgIcon;
```

```css
.svg-icon {
    width: 24px;
    height: 24px;
    display: inline-block;
    vertical-align: middle;
    user-select: none;
    transition: fill 0.2s ease-out, fill-opacity 0.2s ease-out;
}
```
